<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <TargetExt>.gha</TargetExt>
    <OutputType>Library</OutputType>
    <Company>Robert McNeel &amp; Associates</Company>
    <Copyright>Copyright (c) 2012-25, Robert McNeel &amp; Associates</Copyright>
    <Description>MooseGh component for Grasshopper</Description>
    <Product>MooseGh</Product>
    <Version>8.0</Version>
    <BaseOutputPath>..\Bin\</BaseOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;NU1701</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;NU1701</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MooseCommon\MooseCommon.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="8.16.25042.13001" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
  </ItemGroup>
</Project>